services:
  mysql-db:
    container_name: pickypicky-db
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - pickypicky-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pickypicky
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

volumes:
    pickypicky-db: